export const vehicles = [
  {
    sno: 1,
    name: "Acura",
    brandname: "CL Models (4)",
    motorbrand: "AJP",
    motormodel: "Tornado Naked Tre",
  },
  {
    sno: 2,
    name: "Alfa Romeo",
    brandname: "2.2CL",
    motorbrand: "Aprilia",
    motormodel: "XVS 650A Drag Star",
  },
  {
    sno: 3,
    name: "AMC",
    brandname: "2.3CL",
    motorbrand: "Headbanger",
    motormodel: "New Cygnus 125",
  },
  {
    sno: 4,
    name: "Aston Martin",
    brandname: "3.0CL",
    motorbrand: "Ducati",
    motormodel: "GTS 1000",
  },
  {
    sno: 5,
    name: "Audi",
    brandname: "3.2CL",
    motorbrand: "Paton",
    motormodel: "Miami 250",
  },
  {
    sno: 6,
    name: "Avanti",
    brandname: "ILX",
    motorbrand: "Magni",
    motormodel: "Hollywood 50",
  },
  {
    sno: 7,
    name: "Bentley",
    brandname: "Integra",
    motorbrand: "Vectrix",
    motormodel: "Cygnus 125",
  },
  {
    sno: 8,
    name: "BMW",
    brandname: "Legend",
    motorbrand: "BMW",
    motormodel: "Majesty 180",
  },
  {
    sno: 9,
    name: "Buick",
    brandname: "MDX",
    motorbrand: "CR&S",
    motormodel: "Tricity 125",
  },
  {
    sno: 10,
    name: "Cadillac",
    brandname: "NSX",
    motorbrand: "TM Racing",
    motormodel: "XVS 1300 Custom",
  },
  {
    sno: 11,
    name: "Chevrolet",
    brandname: "RDX",
    motorbrand: "Cagiva",
    motormodel: "D'elight",
  },
  {
    sno: 12,
    name: "Chrysler",
    brandname: "RL Models (2)",
    motorbrand: "Maico",
    motormodel: "EN 450",
  },
  {
    sno: 13,
    name: "Daewoo",
    brandname: "3.5 RL",
    motorbrand: "Hyosung",
    motormodel: "BW'S 125",
  },
  {
    sno: 14,
    name: "Daihatsu",
    brandname: "RL",
    motorbrand: "Montesa",
    motormodel: "XVS 950A Midnight Star",
  },
  {
    sno: 15,
    name: "Datsun",
    brandname: "RSX",
    motorbrand: "Nipponia",
    motormodel: "XT 1200 Z Super T",
  },
  {
    sno: 16,
    name: "DeLorean",
    brandname: "SLX",
    motorbrand: "Italjet",
    motormodel: "Roc 50",
  },
  {
    sno: 17,
    name: "Dodge",
    brandname: "TL Models (3)",
    motorbrand: "MV Agusta",
    motormodel: "Bilbao 50",
  },
  {
    sno: 18,
    name: "Eagle",
    brandname: "2.5TL",
    motorbrand: "Scorpa",
    motormodel: "Roadmaster",
  },
  {
    sno: 19,
    name: "Ferrari",
    brandname: "3.2TL",
    motorbrand: "Vertemati",
    motormodel: "X-Max 400",
  },
  {
    sno: 20,
    name: "FIAT",
    brandname: "TL",
    motorbrand: "Malaguti",
    motormodel: "Evo 300",
  },
  {
    sno: 21,
    name: "Fisker",
    brandname: "TSX",
    motorbrand: "Yamaha",
    motormodel: "DRD PRO 50",
  },
  {
    sno: 22,
    name: "Ford",
    brandname: "Vigor",
    motorbrand: "Sachs",
    motormodel: "Maxter 125",
  },
  {
    sno: 23,
    name: "Freightliner",
    brandname: "ZDX",
    motorbrand: "Rieju",
    motormodel: "Gunner",
  },
  {
    sno: 24,
    name: "Geo",
    brandname: "Vincent",
    motorbrand: "Terra Modena",
    motormodel: "XV 535 Virago",
  },
  {
    sno: 25,
    name: "GMC",
    brandname: "164",
    motorbrand: "Laverda",
    motormodel: "Evo 290",
  },
  {
    sno: 26,
    name: "Honda",
    brandname: "8C Competizione",
    motorbrand: "Peugeot",
    motormodel: "Magnum",
  },
  {
    sno: 27,
    name: "HUMMER",
    brandname: "GTV-6",
    motorbrand: "Quantya",
    motormodel: "Arlen Ness Vision",
  },
  {
    sno: 28,
    name: "Hyundai",
    brandname: "Milano",
    motorbrand: "Ghezzi-Brian",
    motormodel: "Supermotard 50",
  },
  {
    sno: 29,
    name: "Infiniti",
    brandname: "Spider",
    motorbrand: "Jawa",
    motormodel: "Xenter 125",
  },
  {
    sno: 30,
    name: "Isuzu",
    brandname: "Conqueror",
    motorbrand: "Garelli",
    motormodel: "Thruxton 865",
  },
  {
    sno: 31,
    name: "Jaguar",
    brandname: "Alliance",
    motorbrand: "Axy",
    motormodel: "Cross Roads",
  },
  {
    sno: 32,
    name: "Jeep",
    brandname: "Concord",
    motorbrand: "Nox",
    motormodel: "Tiger 800",
  },
  {
    sno: 33,
    name: "Kia",
    brandname: "Eagle",
    motorbrand: "Bultaco",
    motormodel: "Hammer",
  },
  {
    sno: 34,
    name: "Lamborghini",
    brandname: "Encore",
    motorbrand: "Steed",
    motormodel: "SpeedMaster",
  },
  {
    sno: 35,
    name: "Lancia",
    brandname: "Spirit",
    motorbrand: "Siamoto",
    motormodel: "Quadra",
  },
  {
    sno: 36,
    name: "Land Rover",
    brandname: "Silver",
    motorbrand: "Husaberg",
    motormodel: "Daytona 650",
  },
  {
    sno: 37,
    name: "Lexus",
    brandname: "DB7",
    motorbrand: "Hupper",
    motormodel: "Vegas",
  },
  {
    sno: 38,
    name: "Lincoln",
    brandname: "DB9",
    motorbrand: "Moto Bellini",
    motormodel: "Stalker 50",
  },
  {
    sno: 39,
    name: "Lotus",
    brandname: "DBS",
    motorbrand: "Borile",
    motormodel: "Tricker 250",
  },
  {
    sno: 40,
    name: "Maserati",
    brandname: "Lagonda",
    motorbrand: "Millepercento",
    motormodel: "Fazer 8",
  },
  {
    sno: 41,
    name: "Maybach",
    brandname: "Rapide",
    motorbrand: "Derbi",
    motormodel: "Vity 125",
  },
  {
    sno: 42,
    name: "Mazda",
    brandname: "V12 Vantage",
    motorbrand: "Polini",
    motormodel: "Cygnus X 125",
  },
  {
    sno: 43,
    name: "McLaren",
    brandname: "V8 Vantage",
    motorbrand: "Ecomission",
    motormodel: "YZF 600 R Thundercat",
  },
  {
    sno: 44,
    name: "Mercedes-Benz",
    brandname: "Vanquish",
    motorbrand: "Fantic Motor",
    motormodel: "MT-01",
  },
  {
    sno: 45,
    name: "Mercury",
    brandname: "Virage",
    motorbrand: "Husqvarna",
    motormodel: "DRD Edition",
  },
  {
    sno: 46,
    name: "Merkur",
    brandname: "Gold",
    motorbrand: "Ossa",
    motormodel: "Coguar 125",
  },
  {
    sno: 47,
    name: "MINI",
    brandname: "100",
    motorbrand: "Benelli",
    motormodel: "Romano 150",
  },
  {
    sno: 48,
    name: "Mitsubishi",
    brandname: "200",
    motorbrand: "CPI",
    motormodel: "Adventurer",
  },
  {
    sno: 49,
    name: "Nissan",
    brandname: "4000",
    motorbrand: "Green Mobility Italia",
    motormodel: "Thruxton 900",
  },
  {
    sno: 50,
    name: "Oldsmobile",
    brandname: "Platinum",
    motorbrand: "Aspess Power",
    motormodel: "X Motion 300",
  },
  {
    sno: 51,
    name: "Peugeot",
    brandname: "80",
    motorbrand: "Quadro",
    motormodel: "RR Enduro 520",
  },
  {
    sno: 52,
    name: "Plymouth",
    brandname: "Citation",
    motorbrand: "Kreidler",
    motormodel: "650 TK Touring",
  },
  {
    sno: 53,
    name: "Pontiac",
    brandname: "Nubira",
    motorbrand: "Victory",
    motormodel: "XV 125 Virago",
  },
  {
    sno: 54,
    name: "Porsche",
    brandname: "A4",
    motorbrand: "Azel",
    motormodel: "Bull&t 50",
  },
  {
    sno: 55,
    name: "RAM",
    brandname: "A5",
    motorbrand: "Keeway",
    motormodel: "Legend",
  },
  {
    sno: 56,
    name: "Renault",
    brandname: "A6",
    motorbrand: "Gilera",
    motormodel: "Lightning CityX XB12",
  },
  {
    sno: 57,
    name: "Rolls-Royce",
    brandname: "A7",
    motorbrand: "Daelim",
    motormodel: "Reload",
  },
  {
    sno: 58,
    name: "Saab",
    brandname: "A8",
    motorbrand: "Bimota",
    motormodel: "XT 600",
  },
  {
    sno: 59,
    name: "Saturn",
    brandname: "Allroad",
    motorbrand: "Mondial",
    motormodel: "Tiger 1200",
  },
  {
    sno: 60,
    name: "Scion",
    brandname: "Cabriolet",
    motorbrand: "Indian",
    motormodel: "Trophy 1215",
  },
  {
    sno: 61,
    name: "smart",
    brandname: "Coupe",
    motorbrand: "Honda Dall'Ara",
    motormodel: "UH 750 Retro Solo",
  },
  {
    sno: 62,
    name: "SRT",
    brandname: "Q3",
    motorbrand: "CF Moto",
    motormodel: "Vroom 50",
  },
  {
    sno: 63,
    name: "Sterling",
    brandname: "Q5",
    motorbrand: "Sherco",
    motormodel: "XJ 600 Diversion",
  },
  {
    sno: 64,
    name: "Subaru",
    brandname: "Q7",
    motorbrand: "Suzuki Valenti",
    motormodel: "SH 150",
  },
  {
    sno: 65,
    name: "Suzuki",
    brandname: "Quattro",
    motorbrand: "WT Motors",
    motormodel: "Mantra DB3",
  },
  {
    sno: 66,
    name: "Tesla",
    brandname: "R8",
    motorbrand: "Linhai",
    motormodel: "Versity 300",
  },
  {
    sno: 67,
    name: "Toyota",
    brandname: "RS 4",
    motorbrand: "Peda Motor",
    motormodel: "Onyx 50",
  },
  {
    sno: 68,
    name: "Triumph",
    brandname: "RS 5",
    motorbrand: "Harley-Davidson",
    motormodel: "Century 1130 Racer",
  },
  {
    sno: 69,
    name: "Volkswagen",
    brandname: "RS 6",
    motorbrand: "Norton",
    motormodel: "Mainstreet 300",
  },
  {
    sno: 70,
    name: "Volvo",
    brandname: "S4",
    motorbrand: "Lambretta",
    motormodel: "Rev 3 270",
  },
  {
    sno: 71,
    name: "Yugo",
    brandname: "S5",
    motorbrand: "Vor",
    motormodel: "Atlantic 500",
  },
];
